services:
  ros2-mission:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2-mission
    environment:
      - LIBGL_ALWAYS_INDIRECT=1
      - ROS_DOMAIN_ID=1
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///connections/cycloneDDS_profile.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws:/ros2_ws
      - ./connections:/connections
      - /dev/ttyUSB0:/dev/ttyUSB0
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ipc: host
    privileged: true
    tty: true
    stdin_open: true
    network_mode: host
    entrypoint: ["/ros_entrypoint.sh"]
    command: bash