version: '3'

services:
  ros2-mission:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2-mission
    environment:
      - LIBGL_ALWAYS_INDIRECT=1
      - ROS_DOMAIN_ID=69
      - ROS_LOCALHOST_ONLY=0
      - RMWIMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws:/ros2_ws
      - ./connections:/connections
      - /dev/ttyUSB0:/dev/ttyUSB0
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: ["/ros_entrypoint.sh"]
    command: bash